server:
  port: 8047
  max-http-header-size: 10240
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  profiles:
    active: container
  application:
    name: bins-global-id-provider

log:
  path: bins-global-id-provider