gid:
  name: com.bins.global.id
  snowflake:
    enable: true
    zk:
      address: 127.0.0.1:2181
    port: 8840

spring:
  application:
    name: bins-global-id-provider
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
  dubbo:
    application:
      name: bins-global-id-provider
      qos-port: 22237
      version: 1.0.0
    protocol:
      id: dubbo
      name: dubbo
      port: 22997
      threadpool: fixed
      threads: 500
    consumer:
      check: false
      version: 0.0.1
    provider:
      version: 0.0.1
      timeout: 3000
      retries: -1
    registry:
      check: false
      protocol: zookeeper
      address: 127.0.0.1:2181
    gra:
      group: dev-group

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true